name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'  # This is the Eclipse Temurin distribution

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Capture Build Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/

      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports-${{ matrix.os }}-java${{ matrix.java }}
          path: build/reports/